% define function (function must be named the same as the script to work)
function []=NAPLS_EEG_array(i)

	% add a line here to get your list of files to iterate over, same as if you were going to do a for loop
	% use the variable i to index that list, except instead of the value of i being incremented by your for loop, i is passed to this script as an argument, and n versions of the script are run in parallel
	
	% replace lines below with your desired code to be run for each subject
	% if you look at the output log files generated by the code below, each will print "test" followed by a different integer corresponding to the last integer in the log file name (aka the index of the job array)
	fprintf("test")
	fprintf("\n")
	% print array index that was passed to this script as an argument, set to the variable i in this script
	fprintf('%d', i)

% end function
end
